// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/node_modules/dumi/theme-default/slots/Navbar/index.js';
