// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { demos as dm0, frontmatter as fm0, toc as toc0, texts as txt0 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/js/ArrayRemoveDuplication/ArrayRemoveDuplication.md?type=meta';
import { demos as dm1, frontmatter as fm1, toc as toc1, texts as txt1 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/appendix/compiler-options.md?type=meta';
import { demos as dm2, frontmatter as fm2, toc as toc2, texts as txt2 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/8vue-reactive-dep-watch.md?type=meta';
import { demos as dm3, frontmatter as fm3, toc as toc3, texts as txt3 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/appendix/vue-global-api.md?type=meta';
import { demos as dm4, frontmatter as fm4, toc as toc4, texts as txt4 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/81vue-lexical-analysis.md?type=meta';
import { demos as dm5, frontmatter as fm5, toc as toc5, texts as txt5 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/appendix/vue-prototype.md?type=meta';
import { demos as dm6, frontmatter as fm6, toc as toc6, texts as txt6 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/selectionSort/index.md?type=meta';
import { demos as dm7, frontmatter as fm7, toc as toc7, texts as txt7 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/countingSort/index.md?type=meta';
import { demos as dm8, frontmatter as fm8, toc as toc8, texts as txt8 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/80vue-compiler-start.md?type=meta';
import { demos as dm9, frontmatter as fm9, toc as toc9, texts as txt9 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/appendix/shared-util.md?type=meta';
import { demos as dm10, frontmatter as fm10, toc as toc10, texts as txt10 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/BubbleSort/index.md?type=meta';
import { demos as dm11, frontmatter as fm11, toc as toc11, texts as txt11 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/insertSort/index.md?type=meta';
import { demos as dm12, frontmatter as fm12, toc as toc12, texts as txt12 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/appendix/core-util.md?type=meta';
import { demos as dm13, frontmatter as fm13, toc as toc13, texts as txt13 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/mergeSort/index.md?type=meta';
import { demos as dm14, frontmatter as fm14, toc as toc14, texts as txt14 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/quickSort/index.md?type=meta';
import { demos as dm15, frontmatter as fm15, toc as toc15, texts as txt15 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/radixSort/index.md?type=meta';
import { demos as dm16, frontmatter as fm16, toc as toc16, texts as txt16 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/shellSort/index.md?type=meta';
import { demos as dm17, frontmatter as fm17, toc as toc17, texts as txt17 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/appendix/web-util.md?type=meta';
import { demos as dm18, frontmatter as fm18, toc as toc18, texts as txt18 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/2vue-constructor.md?type=meta';
import { demos as dm19, frontmatter as fm19, toc as toc19, texts as txt19 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/86vue-vdom-patch.md?type=meta';
import { demos as dm20, frontmatter as fm20, toc as toc20, texts as txt20 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/appendix/vue-ins.md?type=meta';
import { demos as dm21, frontmatter as fm21, toc as toc21, texts as txt21 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/EnvironmentConfiguration/nginx/index.md?type=meta';
import { demos as dm22, frontmatter as fm22, toc as toc22, texts as txt22 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/heapify/index.md?type=meta';
import { demos as dm23, frontmatter as fm23, toc as toc23, texts as txt23 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/10vue-core-idea.md?type=meta';
import { demos as dm24, frontmatter as fm24, toc as toc24, texts as txt24 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/6vue-init-start.md?type=meta';
import { demos as dm25, frontmatter as fm25, toc as toc25, texts as txt25 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/83vue-parsing-2.md?type=meta';
import { demos as dm26, frontmatter as fm26, toc as toc26, texts as txt26 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/9vue-state-init.md?type=meta';
import { demos as dm27, frontmatter as fm27, toc as toc27, texts as txt27 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/4vue-normalize.md?type=meta';
import { demos as dm28, frontmatter as fm28, toc as toc28, texts as txt28 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/appendix/index.md?type=meta';
import { demos as dm29, frontmatter as fm29, toc as toc29, texts as txt29 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/EnvironmentConfiguration/git/index.md?type=meta';
import { demos as dm30, frontmatter as fm30, toc as toc30, texts as txt30 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/EnvironmentConfiguration/gpt/index.md?type=meta';
import { demos as dm31, frontmatter as fm31, toc as toc31, texts as txt31 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/EnvironmentConfiguration/npm/index.md?type=meta';
import { demos as dm32, frontmatter as fm32, toc as toc32, texts as txt32 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/EnvironmentConfiguration/vpn/index.md?type=meta';
import { demos as dm33, frontmatter as fm33, toc as toc33, texts as txt33 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/7vue-reactive.md?type=meta';
import { demos as dm34, frontmatter as fm34, toc as toc34, texts as txt34 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/82vue-parsing.md?type=meta';
import { demos as dm35, frontmatter as fm35, toc as toc35, texts as txt35 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/84vue-codegen.md?type=meta';
import { demos as dm36, frontmatter as fm36, toc as toc36, texts as txt36 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/InterviewTips/hrTest.md?type=meta';
import { demos as dm37, frontmatter as fm37, toc as toc37, texts as txt37 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/js/deepCopy/deepCopy.md?type=meta';
import { demos as dm38, frontmatter as fm38, toc as toc38, texts as txt38 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/1start-learn.md?type=meta';
import { demos as dm39, frontmatter as fm39, toc as toc39, texts as txt39 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/3vue-example.md?type=meta';
import { demos as dm40, frontmatter as fm40, toc as toc40, texts as txt40 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/appendix/ast.md?type=meta';
import { demos as dm41, frontmatter as fm41, toc as toc41, texts as txt41 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/EnvironmentConfiguration/n/index.md?type=meta';
import { demos as dm42, frontmatter as fm42, toc as toc42, texts as txt42 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/InterviewTips/index.md?type=meta';
import { demos as dm43, frontmatter as fm43, toc as toc43, texts as txt43 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/LIS/index.md?type=meta';
import { demos as dm44, frontmatter as fm44, toc as toc44, texts as txt44 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/5vue-merge.md?type=meta';
import { demos as dm45, frontmatter as fm45, toc as toc45, texts as txt45 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/85vue-vdom.md?type=meta';
import { demos as dm46, frontmatter as fm46, toc as toc46, texts as txt46 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/EnvironmentConfiguration/index.md?type=meta';
import { demos as dm47, frontmatter as fm47, toc as toc47, texts as txt47 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/js/Object/Object.md?type=meta';
import { demos as dm48, frontmatter as fm48, toc as toc48, texts as txt48 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/js/String/String.md?type=meta';
import { demos as dm49, frontmatter as fm49, toc as toc49, texts as txt49 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/index.md?type=meta';
import { demos as dm50, frontmatter as fm50, toc as toc50, texts as txt50 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/engineering/gw.md?type=meta';
import { demos as dm51, frontmatter as fm51, toc as toc51, texts as txt51 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/js/Array/Array.md?type=meta';
import { demos as dm52, frontmatter as fm52, toc as toc52, texts as txt52 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/browser/index.md?type=meta';
import { demos as dm53, frontmatter as fm53, toc as toc53, texts as txt53 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/promise/index.md?type=meta';
import { demos as dm54, frontmatter as fm54, toc as toc54, texts as txt54 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/art/index.md?type=meta';
import { demos as dm55, frontmatter as fm55, toc as toc55, texts as txt55 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/js/util/util.md?type=meta';
import { demos as dm56, frontmatter as fm56, toc as toc56, texts as txt56 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/react/index.md?type=meta';
import { demos as dm57, frontmatter as fm57, toc as toc57, texts as txt57 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/html/index.md?type=meta';
import { demos as dm58, frontmatter as fm58, toc as toc58, texts as txt58 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/http/index.md?type=meta';
import { demos as dm59, frontmatter as fm59, toc as toc59, texts as txt59 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/js/Reg/reg.md?type=meta';
import { demos as dm60, frontmatter as fm60, toc as toc60, texts as txt60 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/self/index.md?type=meta';
import { demos as dm61, frontmatter as fm61, toc as toc61, texts as txt61 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/taro/index.md?type=meta';
import { demos as dm62, frontmatter as fm62, toc as toc62, texts as txt62 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/css/index.md?type=meta';
import { demos as dm63, frontmatter as fm63, toc as toc63, texts as txt63 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/index.md?type=meta';
import { demos as dm64, frontmatter as fm64, toc as toc64, texts as txt64 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/js/index.md?type=meta';
import { demos as dm65, frontmatter as fm65, toc as toc65, texts as txt65 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/om/index.md?type=meta';
import { demos as dm66, frontmatter as fm66, toc as toc66, texts as txt66 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/ui/index.md?type=meta';
import { demos as dm67, frontmatter as fm67, toc as toc67, texts as txt67 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/index.md?type=meta';
import { demos as dm68, frontmatter as fm68, toc as toc68, texts as txt68 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/js/js.md?type=meta';
import { demos as dm69, frontmatter as fm69, toc as toc69, texts as txt69 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/index.md?type=meta';

export { components } from './atoms';
export { tabs } from './tabs';

export const filesMeta = {
  'docs/FrontEndCode/js/ArrayRemoveDuplication/ArrayRemoveDuplication': {
    frontmatter: fm0,
    toc: toc0,
    texts: txt0,
    demos: dm0,
  },
  'docs/FrontEndCode/vue/art/appendix/compiler-options': {
    frontmatter: fm1,
    toc: toc1,
    texts: txt1,
    demos: dm1,
  },
  'docs/FrontEndCode/vue/art/8vue-reactive-dep-watch': {
    frontmatter: fm2,
    toc: toc2,
    texts: txt2,
    demos: dm2,
  },
  'docs/FrontEndCode/vue/art/appendix/vue-global-api': {
    frontmatter: fm3,
    toc: toc3,
    texts: txt3,
    demos: dm3,
  },
  'docs/FrontEndCode/vue/art/81vue-lexical-analysis': {
    frontmatter: fm4,
    toc: toc4,
    texts: txt4,
    demos: dm4,
  },
  'docs/FrontEndCode/vue/art/appendix/vue-prototype': {
    frontmatter: fm5,
    toc: toc5,
    texts: txt5,
    demos: dm5,
  },
  'docs/FrontEndCode/algorithm/selectionSort/index': {
    frontmatter: fm6,
    toc: toc6,
    texts: txt6,
    demos: dm6,
  },
  'docs/FrontEndCode/algorithm/countingSort/index': {
    frontmatter: fm7,
    toc: toc7,
    texts: txt7,
    demos: dm7,
  },
  'docs/FrontEndCode/vue/art/80vue-compiler-start': {
    frontmatter: fm8,
    toc: toc8,
    texts: txt8,
    demos: dm8,
  },
  'docs/FrontEndCode/vue/art/appendix/shared-util': {
    frontmatter: fm9,
    toc: toc9,
    texts: txt9,
    demos: dm9,
  },
  'docs/FrontEndCode/algorithm/BubbleSort/index': {
    frontmatter: fm10,
    toc: toc10,
    texts: txt10,
    demos: dm10,
  },
  'docs/FrontEndCode/algorithm/insertSort/index': {
    frontmatter: fm11,
    toc: toc11,
    texts: txt11,
    demos: dm11,
  },
  'docs/FrontEndCode/vue/art/appendix/core-util': {
    frontmatter: fm12,
    toc: toc12,
    texts: txt12,
    demos: dm12,
  },
  'docs/FrontEndCode/algorithm/mergeSort/index': {
    frontmatter: fm13,
    toc: toc13,
    texts: txt13,
    demos: dm13,
  },
  'docs/FrontEndCode/algorithm/quickSort/index': {
    frontmatter: fm14,
    toc: toc14,
    texts: txt14,
    demos: dm14,
  },
  'docs/FrontEndCode/algorithm/radixSort/index': {
    frontmatter: fm15,
    toc: toc15,
    texts: txt15,
    demos: dm15,
  },
  'docs/FrontEndCode/algorithm/shellSort/index': {
    frontmatter: fm16,
    toc: toc16,
    texts: txt16,
    demos: dm16,
  },
  'docs/FrontEndCode/vue/art/appendix/web-util': {
    frontmatter: fm17,
    toc: toc17,
    texts: txt17,
    demos: dm17,
  },
  'docs/FrontEndCode/vue/art/2vue-constructor': {
    frontmatter: fm18,
    toc: toc18,
    texts: txt18,
    demos: dm18,
  },
  'docs/FrontEndCode/vue/art/86vue-vdom-patch': {
    frontmatter: fm19,
    toc: toc19,
    texts: txt19,
    demos: dm19,
  },
  'docs/FrontEndCode/vue/art/appendix/vue-ins': {
    frontmatter: fm20,
    toc: toc20,
    texts: txt20,
    demos: dm20,
  },
  'docs/EnvironmentConfiguration/nginx/index': {
    frontmatter: fm21,
    toc: toc21,
    texts: txt21,
    demos: dm21,
  },
  'docs/FrontEndCode/algorithm/heapify/index': {
    frontmatter: fm22,
    toc: toc22,
    texts: txt22,
    demos: dm22,
  },
  'docs/FrontEndCode/vue/art/10vue-core-idea': {
    frontmatter: fm23,
    toc: toc23,
    texts: txt23,
    demos: dm23,
  },
  'docs/FrontEndCode/vue/art/6vue-init-start': {
    frontmatter: fm24,
    toc: toc24,
    texts: txt24,
    demos: dm24,
  },
  'docs/FrontEndCode/vue/art/83vue-parsing-2': {
    frontmatter: fm25,
    toc: toc25,
    texts: txt25,
    demos: dm25,
  },
  'docs/FrontEndCode/vue/art/9vue-state-init': {
    frontmatter: fm26,
    toc: toc26,
    texts: txt26,
    demos: dm26,
  },
  'docs/FrontEndCode/vue/art/4vue-normalize': {
    frontmatter: fm27,
    toc: toc27,
    texts: txt27,
    demos: dm27,
  },
  'docs/FrontEndCode/vue/art/appendix/index': {
    frontmatter: fm28,
    toc: toc28,
    texts: txt28,
    demos: dm28,
  },
  'docs/EnvironmentConfiguration/git/index': {
    frontmatter: fm29,
    toc: toc29,
    texts: txt29,
    demos: dm29,
  },
  'docs/EnvironmentConfiguration/gpt/index': {
    frontmatter: fm30,
    toc: toc30,
    texts: txt30,
    demos: dm30,
  },
  'docs/EnvironmentConfiguration/npm/index': {
    frontmatter: fm31,
    toc: toc31,
    texts: txt31,
    demos: dm31,
  },
  'docs/EnvironmentConfiguration/vpn/index': {
    frontmatter: fm32,
    toc: toc32,
    texts: txt32,
    demos: dm32,
  },
  'docs/FrontEndCode/vue/art/7vue-reactive': {
    frontmatter: fm33,
    toc: toc33,
    texts: txt33,
    demos: dm33,
  },
  'docs/FrontEndCode/vue/art/82vue-parsing': {
    frontmatter: fm34,
    toc: toc34,
    texts: txt34,
    demos: dm34,
  },
  'docs/FrontEndCode/vue/art/84vue-codegen': {
    frontmatter: fm35,
    toc: toc35,
    texts: txt35,
    demos: dm35,
  },
  'docs/FrontEndCode/InterviewTips/hrTest': {
    frontmatter: fm36,
    toc: toc36,
    texts: txt36,
    demos: dm36,
  },
  'docs/FrontEndCode/js/deepCopy/deepCopy': {
    frontmatter: fm37,
    toc: toc37,
    texts: txt37,
    demos: dm37,
  },
  'docs/FrontEndCode/vue/art/1start-learn': {
    frontmatter: fm38,
    toc: toc38,
    texts: txt38,
    demos: dm38,
  },
  'docs/FrontEndCode/vue/art/3vue-example': {
    frontmatter: fm39,
    toc: toc39,
    texts: txt39,
    demos: dm39,
  },
  'docs/FrontEndCode/vue/art/appendix/ast': {
    frontmatter: fm40,
    toc: toc40,
    texts: txt40,
    demos: dm40,
  },
  'docs/EnvironmentConfiguration/n/index': {
    frontmatter: fm41,
    toc: toc41,
    texts: txt41,
    demos: dm41,
  },
  'docs/FrontEndCode/InterviewTips/index': {
    frontmatter: fm42,
    toc: toc42,
    texts: txt42,
    demos: dm42,
  },
  'docs/FrontEndCode/algorithm/LIS/index': {
    frontmatter: fm43,
    toc: toc43,
    texts: txt43,
    demos: dm43,
  },
  'docs/FrontEndCode/vue/art/5vue-merge': {
    frontmatter: fm44,
    toc: toc44,
    texts: txt44,
    demos: dm44,
  },
  'docs/FrontEndCode/vue/art/85vue-vdom': {
    frontmatter: fm45,
    toc: toc45,
    texts: txt45,
    demos: dm45,
  },
  'docs/EnvironmentConfiguration/index': {
    frontmatter: fm46,
    toc: toc46,
    texts: txt46,
    demos: dm46,
  },
  'docs/FrontEndCode/js/Object/Object': {
    frontmatter: fm47,
    toc: toc47,
    texts: txt47,
    demos: dm47,
  },
  'docs/FrontEndCode/js/String/String': {
    frontmatter: fm48,
    toc: toc48,
    texts: txt48,
    demos: dm48,
  },
  'docs/FrontEndCode/algorithm/index': {
    frontmatter: fm49,
    toc: toc49,
    texts: txt49,
    demos: dm49,
  },
  'docs/FrontEndCode/engineering/gw': {
    frontmatter: fm50,
    toc: toc50,
    texts: txt50,
    demos: dm50,
  },
  'docs/FrontEndCode/js/Array/Array': {
    frontmatter: fm51,
    toc: toc51,
    texts: txt51,
    demos: dm51,
  },
  'docs/FrontEndCode/browser/index': {
    frontmatter: fm52,
    toc: toc52,
    texts: txt52,
    demos: dm52,
  },
  'docs/FrontEndCode/promise/index': {
    frontmatter: fm53,
    toc: toc53,
    texts: txt53,
    demos: dm53,
  },
  'docs/FrontEndCode/vue/art/index': {
    frontmatter: fm54,
    toc: toc54,
    texts: txt54,
    demos: dm54,
  },
  'docs/FrontEndCode/js/util/util': {
    frontmatter: fm55,
    toc: toc55,
    texts: txt55,
    demos: dm55,
  },
  'docs/FrontEndCode/react/index': {
    frontmatter: fm56,
    toc: toc56,
    texts: txt56,
    demos: dm56,
  },
  'docs/FrontEndCode/html/index': {
    frontmatter: fm57,
    toc: toc57,
    texts: txt57,
    demos: dm57,
  },
  'docs/FrontEndCode/http/index': {
    frontmatter: fm58,
    toc: toc58,
    texts: txt58,
    demos: dm58,
  },
  'docs/FrontEndCode/js/Reg/reg': {
    frontmatter: fm59,
    toc: toc59,
    texts: txt59,
    demos: dm59,
  },
  'docs/FrontEndCode/self/index': {
    frontmatter: fm60,
    toc: toc60,
    texts: txt60,
    demos: dm60,
  },
  'docs/FrontEndCode/taro/index': {
    frontmatter: fm61,
    toc: toc61,
    texts: txt61,
    demos: dm61,
  },
  'docs/FrontEndCode/css/index': {
    frontmatter: fm62,
    toc: toc62,
    texts: txt62,
    demos: dm62,
  },
  'docs/FrontEndCode/vue/index': {
    frontmatter: fm63,
    toc: toc63,
    texts: txt63,
    demos: dm63,
  },
  'docs/FrontEndCode/js/index': {
    frontmatter: fm64,
    toc: toc64,
    texts: txt64,
    demos: dm64,
  },
  'docs/FrontEndCode/om/index': {
    frontmatter: fm65,
    toc: toc65,
    texts: txt65,
    demos: dm65,
  },
  'docs/FrontEndCode/ui/index': {
    frontmatter: fm66,
    toc: toc66,
    texts: txt66,
    demos: dm66,
  },
  'docs/FrontEndCode/index': {
    frontmatter: fm67,
    toc: toc67,
    texts: txt67,
    demos: dm67,
  },
  'docs/FrontEndCode/js/js': {
    frontmatter: fm68,
    toc: toc68,
    texts: txt68,
    demos: dm68,
  },
  'docs/index': {
    frontmatter: fm69,
    toc: toc69,
    texts: txt69,
    demos: dm69,
  },
}

// generate demos data in runtime, for reuse route.id to reduce bundle size
export const demos = Object.entries(filesMeta).reduce((acc, [id, meta]) => {
  // append route id to demo
  Object.values(meta.demos).forEach((demo) => {
    demo.routeId = id;
  });
  // merge demos
  Object.assign(acc, meta.demos);

  // remove demos from meta, to avoid deep clone demos in umi routes/children compatible logic
  delete meta.demos;

  return acc;
}, {});
