// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { demos as dm0, frontmatter as fm0, toc as toc0, texts as txt0 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/js/ArrayRemoveDuplication/ArrayRemoveDuplication.md?type=meta';
import { demos as dm1, frontmatter as fm1, toc as toc1, texts as txt1 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/selectionSort/index.md?type=meta';
import { demos as dm2, frontmatter as fm2, toc as toc2, texts as txt2 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/countingSort/index.md?type=meta';
import { demos as dm3, frontmatter as fm3, toc as toc3, texts as txt3 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/BubbleSort/index.md?type=meta';
import { demos as dm4, frontmatter as fm4, toc as toc4, texts as txt4 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/insertSort/index.md?type=meta';
import { demos as dm5, frontmatter as fm5, toc as toc5, texts as txt5 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/mergeSort/index.md?type=meta';
import { demos as dm6, frontmatter as fm6, toc as toc6, texts as txt6 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/quickSort/index.md?type=meta';
import { demos as dm7, frontmatter as fm7, toc as toc7, texts as txt7 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/radixSort/index.md?type=meta';
import { demos as dm8, frontmatter as fm8, toc as toc8, texts as txt8 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/shellSort/index.md?type=meta';
import { demos as dm9, frontmatter as fm9, toc as toc9, texts as txt9 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/EnvironmentConfiguration/nginx/index.md?type=meta';
import { demos as dm10, frontmatter as fm10, toc as toc10, texts as txt10 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/heapify/index.md?type=meta';
import { demos as dm11, frontmatter as fm11, toc as toc11, texts as txt11 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/EnvironmentConfiguration/git/index.md?type=meta';
import { demos as dm12, frontmatter as fm12, toc as toc12, texts as txt12 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/EnvironmentConfiguration/gpt/index.md?type=meta';
import { demos as dm13, frontmatter as fm13, toc as toc13, texts as txt13 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/EnvironmentConfiguration/npm/index.md?type=meta';
import { demos as dm14, frontmatter as fm14, toc as toc14, texts as txt14 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/EnvironmentConfiguration/vpn/index.md?type=meta';
import { demos as dm15, frontmatter as fm15, toc as toc15, texts as txt15 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/js/deepCopy/deepCopy.md?type=meta';
import { demos as dm16, frontmatter as fm16, toc as toc16, texts as txt16 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/EnvironmentConfiguration/n/index.md?type=meta';
import { demos as dm17, frontmatter as fm17, toc as toc17, texts as txt17 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/LIS/index.md?type=meta';
import { demos as dm18, frontmatter as fm18, toc as toc18, texts as txt18 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/EnvironmentConfiguration/index.md?type=meta';
import { demos as dm19, frontmatter as fm19, toc as toc19, texts as txt19 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/key/InterviewTips.md?type=meta';
import { demos as dm20, frontmatter as fm20, toc as toc20, texts as txt20 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/js/Object/Object.md?type=meta';
import { demos as dm21, frontmatter as fm21, toc as toc21, texts as txt21 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/js/String/String.md?type=meta';
import { demos as dm22, frontmatter as fm22, toc as toc22, texts as txt22 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/js/promise/index.md?type=meta';
import { demos as dm23, frontmatter as fm23, toc as toc23, texts as txt23 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/algorithm/index.md?type=meta';
import { demos as dm24, frontmatter as fm24, toc as toc24, texts as txt24 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/js/Array/Array.md?type=meta';
import { demos as dm25, frontmatter as fm25, toc as toc25, texts as txt25 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/js/util/util.md?type=meta';
import { demos as dm26, frontmatter as fm26, toc as toc26, texts as txt26 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/key/browser.md?type=meta';
import { demos as dm27, frontmatter as fm27, toc as toc27, texts as txt27 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/react/index.md?type=meta';
import { demos as dm28, frontmatter as fm28, toc as toc28, texts as txt28 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/js/Reg/reg.md?type=meta';
import { demos as dm29, frontmatter as fm29, toc as toc29, texts as txt29 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/key/doSelf.md?type=meta';
import { demos as dm30, frontmatter as fm30, toc as toc30, texts as txt30 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/key/hrTest.md?type=meta';
import { demos as dm31, frontmatter as fm31, toc as toc31, texts as txt31 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/taro/index.md?type=meta';
import { demos as dm32, frontmatter as fm32, toc as toc32, texts as txt32 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/css/index.md?type=meta';
import { demos as dm33, frontmatter as fm33, toc as toc33, texts as txt33 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/key/index.md?type=meta';
import { demos as dm34, frontmatter as fm34, toc as toc34, texts as txt34 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/vue/index.md?type=meta';
import { demos as dm35, frontmatter as fm35, toc as toc35, texts as txt35 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/js/index.md?type=meta';
import { demos as dm36, frontmatter as fm36, toc as toc36, texts as txt36 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/key/html.md?type=meta';
import { demos as dm37, frontmatter as fm37, toc as toc37, texts as txt37 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/key/http.md?type=meta';
import { demos as dm38, frontmatter as fm38, toc as toc38, texts as txt38 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/key/sync.md?type=meta';
import { demos as dm39, frontmatter as fm39, toc as toc39, texts as txt39 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/ui/index.md?type=meta';
import { demos as dm40, frontmatter as fm40, toc as toc40, texts as txt40 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/key/css.md?type=meta';
import { demos as dm41, frontmatter as fm41, toc as toc41, texts as txt41 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/key/gw.md?type=meta';
import { demos as dm42, frontmatter as fm42, toc as toc42, texts as txt42 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/key/js.md?type=meta';
import { demos as dm43, frontmatter as fm43, toc as toc43, texts as txt43 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/key/om.md?type=meta';
import { demos as dm44, frontmatter as fm44, toc as toc44, texts as txt44 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/FrontEndCode/index.md?type=meta';
import { demos as dm45, frontmatter as fm45, toc as toc45, texts as txt45 } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/docs/index.md?type=meta';

export { components } from './atoms';
export { tabs } from './tabs';

export const filesMeta = {
  'docs/FrontEndCode/js/ArrayRemoveDuplication/ArrayRemoveDuplication': {
    frontmatter: fm0,
    toc: toc0,
    texts: txt0,
    demos: dm0,
  },
  'docs/FrontEndCode/algorithm/selectionSort/index': {
    frontmatter: fm1,
    toc: toc1,
    texts: txt1,
    demos: dm1,
  },
  'docs/FrontEndCode/algorithm/countingSort/index': {
    frontmatter: fm2,
    toc: toc2,
    texts: txt2,
    demos: dm2,
  },
  'docs/FrontEndCode/algorithm/BubbleSort/index': {
    frontmatter: fm3,
    toc: toc3,
    texts: txt3,
    demos: dm3,
  },
  'docs/FrontEndCode/algorithm/insertSort/index': {
    frontmatter: fm4,
    toc: toc4,
    texts: txt4,
    demos: dm4,
  },
  'docs/FrontEndCode/algorithm/mergeSort/index': {
    frontmatter: fm5,
    toc: toc5,
    texts: txt5,
    demos: dm5,
  },
  'docs/FrontEndCode/algorithm/quickSort/index': {
    frontmatter: fm6,
    toc: toc6,
    texts: txt6,
    demos: dm6,
  },
  'docs/FrontEndCode/algorithm/radixSort/index': {
    frontmatter: fm7,
    toc: toc7,
    texts: txt7,
    demos: dm7,
  },
  'docs/FrontEndCode/algorithm/shellSort/index': {
    frontmatter: fm8,
    toc: toc8,
    texts: txt8,
    demos: dm8,
  },
  'docs/EnvironmentConfiguration/nginx/index': {
    frontmatter: fm9,
    toc: toc9,
    texts: txt9,
    demos: dm9,
  },
  'docs/FrontEndCode/algorithm/heapify/index': {
    frontmatter: fm10,
    toc: toc10,
    texts: txt10,
    demos: dm10,
  },
  'docs/EnvironmentConfiguration/git/index': {
    frontmatter: fm11,
    toc: toc11,
    texts: txt11,
    demos: dm11,
  },
  'docs/EnvironmentConfiguration/gpt/index': {
    frontmatter: fm12,
    toc: toc12,
    texts: txt12,
    demos: dm12,
  },
  'docs/EnvironmentConfiguration/npm/index': {
    frontmatter: fm13,
    toc: toc13,
    texts: txt13,
    demos: dm13,
  },
  'docs/EnvironmentConfiguration/vpn/index': {
    frontmatter: fm14,
    toc: toc14,
    texts: txt14,
    demos: dm14,
  },
  'docs/FrontEndCode/js/deepCopy/deepCopy': {
    frontmatter: fm15,
    toc: toc15,
    texts: txt15,
    demos: dm15,
  },
  'docs/EnvironmentConfiguration/n/index': {
    frontmatter: fm16,
    toc: toc16,
    texts: txt16,
    demos: dm16,
  },
  'docs/FrontEndCode/algorithm/LIS/index': {
    frontmatter: fm17,
    toc: toc17,
    texts: txt17,
    demos: dm17,
  },
  'docs/EnvironmentConfiguration/index': {
    frontmatter: fm18,
    toc: toc18,
    texts: txt18,
    demos: dm18,
  },
  'docs/FrontEndCode/key/InterviewTips': {
    frontmatter: fm19,
    toc: toc19,
    texts: txt19,
    demos: dm19,
  },
  'docs/FrontEndCode/js/Object/Object': {
    frontmatter: fm20,
    toc: toc20,
    texts: txt20,
    demos: dm20,
  },
  'docs/FrontEndCode/js/String/String': {
    frontmatter: fm21,
    toc: toc21,
    texts: txt21,
    demos: dm21,
  },
  'docs/FrontEndCode/js/promise/index': {
    frontmatter: fm22,
    toc: toc22,
    texts: txt22,
    demos: dm22,
  },
  'docs/FrontEndCode/algorithm/index': {
    frontmatter: fm23,
    toc: toc23,
    texts: txt23,
    demos: dm23,
  },
  'docs/FrontEndCode/js/Array/Array': {
    frontmatter: fm24,
    toc: toc24,
    texts: txt24,
    demos: dm24,
  },
  'docs/FrontEndCode/js/util/util': {
    frontmatter: fm25,
    toc: toc25,
    texts: txt25,
    demos: dm25,
  },
  'docs/FrontEndCode/key/browser': {
    frontmatter: fm26,
    toc: toc26,
    texts: txt26,
    demos: dm26,
  },
  'docs/FrontEndCode/react/index': {
    frontmatter: fm27,
    toc: toc27,
    texts: txt27,
    demos: dm27,
  },
  'docs/FrontEndCode/js/Reg/reg': {
    frontmatter: fm28,
    toc: toc28,
    texts: txt28,
    demos: dm28,
  },
  'docs/FrontEndCode/key/doSelf': {
    frontmatter: fm29,
    toc: toc29,
    texts: txt29,
    demos: dm29,
  },
  'docs/FrontEndCode/key/hrTest': {
    frontmatter: fm30,
    toc: toc30,
    texts: txt30,
    demos: dm30,
  },
  'docs/FrontEndCode/taro/index': {
    frontmatter: fm31,
    toc: toc31,
    texts: txt31,
    demos: dm31,
  },
  'docs/FrontEndCode/css/index': {
    frontmatter: fm32,
    toc: toc32,
    texts: txt32,
    demos: dm32,
  },
  'docs/FrontEndCode/key/index': {
    frontmatter: fm33,
    toc: toc33,
    texts: txt33,
    demos: dm33,
  },
  'docs/FrontEndCode/vue/index': {
    frontmatter: fm34,
    toc: toc34,
    texts: txt34,
    demos: dm34,
  },
  'docs/FrontEndCode/js/index': {
    frontmatter: fm35,
    toc: toc35,
    texts: txt35,
    demos: dm35,
  },
  'docs/FrontEndCode/key/html': {
    frontmatter: fm36,
    toc: toc36,
    texts: txt36,
    demos: dm36,
  },
  'docs/FrontEndCode/key/http': {
    frontmatter: fm37,
    toc: toc37,
    texts: txt37,
    demos: dm37,
  },
  'docs/FrontEndCode/key/sync': {
    frontmatter: fm38,
    toc: toc38,
    texts: txt38,
    demos: dm38,
  },
  'docs/FrontEndCode/ui/index': {
    frontmatter: fm39,
    toc: toc39,
    texts: txt39,
    demos: dm39,
  },
  'docs/FrontEndCode/key/css': {
    frontmatter: fm40,
    toc: toc40,
    texts: txt40,
    demos: dm40,
  },
  'docs/FrontEndCode/key/gw': {
    frontmatter: fm41,
    toc: toc41,
    texts: txt41,
    demos: dm41,
  },
  'docs/FrontEndCode/key/js': {
    frontmatter: fm42,
    toc: toc42,
    texts: txt42,
    demos: dm42,
  },
  'docs/FrontEndCode/key/om': {
    frontmatter: fm43,
    toc: toc43,
    texts: txt43,
    demos: dm43,
  },
  'docs/FrontEndCode/index': {
    frontmatter: fm44,
    toc: toc44,
    texts: txt44,
    demos: dm44,
  },
  'docs/index': {
    frontmatter: fm45,
    toc: toc45,
    texts: txt45,
    demos: dm45,
  },
}

// generate demos data in runtime, for reuse route.id to reduce bundle size
export const demos = Object.entries(filesMeta).reduce((acc, [id, meta]) => {
  // append route id to demo
  Object.values(meta.demos).forEach((demo) => {
    demo.routeId = id;
  });
  // merge demos
  Object.assign(acc, meta.demos);

  // remove demos from meta, to avoid deep clone demos in umi routes/children compatible logic
  delete meta.demos;

  return acc;
}, {});
