// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React, { useState, useEffect, useRef } from 'react';
import { useOutlet, history } from 'dumi';

import nprogress from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/node_modules/nprogress';
import './nprogress.css';

import { SiteContext } from '/Users/renshuaiweidemac/Desktop/localhostProject/blog/node_modules/dumi/dist/client/theme-api/context.js';
import { demos, components } from '../meta';
import { locales } from '../locales/config';

const entryExports = {
  
  
};

export default function DumiContextWrapper() {
  const outlet = useOutlet();
  const [loading, setLoading] = useState(true);
  const prev = useRef(history.location.pathname);

  useEffect(() => {
    return history.listen((next) => {
      if (next.location.pathname !== prev.current) {
        prev.current = next.location.pathname;

        // mark loading when route change, page component will set false when loaded
        setLoading(true);

        // start nprogress
        nprogress.start();

        // scroll to top when route changed
        document.documentElement.scrollTo(0, 0);
      }
    });
  }, []);

  return (
    <SiteContext.Provider value={{
      pkg: {"name":"blog","description":"wgg_blog","version":"0.0.1","license":"MIT","authors":["wgg"]},
      historyType: "browser",
      entryExports,
      demos,
      components,
      locales,
      loading,
      setLoading,
      hostname: undefined,
      themeConfig: {"footer":"<a href=\"http://www.ssdwgg.cn/\" target=\"_blank\" rel=\"noreferrer\">WGG</a> © 2023 design by <a href=\"http://www.ssdwgg.cn/\" target=\"_blank\" rel=\"noreferrer\">WGG</a> | Powered by <a href=\"https://d.umijs.org\" target=\"_blank\" rel=\"noreferrer\">dumi</a>","prefersColor":{"default":"auto","switch":true},"nprogress":true,"name":"WGG_Blog","logo":"/favicon.ico","rtl":true,"showLineNum":true,"socialLinks":{"github":"https://github.com/SSDWGG"}},
      _2_level_nav_available: true,
    }}>
      {outlet}
    </SiteContext.Provider>
  );
}
